server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atguigudb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wql19990322
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: wql19990322
      timeout: 5000
  thymeleaf:
    check-template-location: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml